version: '3.8'

services:
  agent:
    build: .
    container_name: browser-agent
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4-turbo-preview}
      - MODE=server
      - HEADLESS=true
      - PORT=3000
      - HOST=0.0.0.0
      - ALLOWED_DOMAINS=${ALLOWED_DOMAINS}
    volumes:
      - ./screenshots:/app/screenshots
      - ./logs:/app/logs
      - ./traces:/app/traces
    restart: unless-stopped
    mem_limit: 4g
    cpus: 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: agent-network

